# Generated by Django 5.0.3 on 2024-04-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='web_id',
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='edited',
            field=models.IntegerField(default=0),
        ),
    ]
