# Generated by Django 5.0.3 on 2024-04-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_remove_product_slug_remove_product_web_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='item',
        ),
    ]
